services:
  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - MANIM_RENDERER_URL=https://manim-renderer-manim-renderer.5gad6x.easypanel.host
    volumes:
      - ffmpeg_temp:/tmp/ffmpeg-service

volumes:
  ffmpeg_temp:
